import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import notification from './components/notification'
import navbar from './components/navbar'
import footer from './components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {notification()}
        {navbar()}
        {children}   
        {footer()}
        </body>
    </html>
  )
}
